export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const COMMENTS_LIST_SUCCESS = 'COMMENTS_LIST_SUCCESS';
export const COMMENTS_LIST_FAIL = 'COMMENTS_LIST_FAIL';
export const ADD_COMMENT = 'ADD_COMMENT';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';